const std = @import("std");
const schema = @import("schema.zig");

pub const Generator = struct {
    allocator: std.mem.Allocator,
    schema: schema.Schema,

    pub fn init(allocator: std.mem.Allocator, s: schema.Schema) Generator {
        return .{
            .allocator = allocator,
            .schema = s,
        };
    }

    pub fn generate(self: *Generator, writer: *std.Io.Writer) !void {
        try writer.writeAll("// Code generated by dagger-zig-codegen. DO NOT EDIT.\n");
        try writer.writeAll("const std = @import(\"std\");\n\n");
        
        try writer.writeAll("pub const QueryBuilder = struct {\n");
        try writer.writeAll("    pub fn selection(self: *QueryBuilder, name: []const u8, args: anytype) !*QueryBuilder {\n");
        try writer.writeAll("        _ = self; _ = name; _ = args;\n");
        try writer.writeAll("        return error.Unimplemented;\n");
        try writer.writeAll("    }\n");
        try writer.writeAll("};\n\n");

        // Filter and sort types
        var scalars = std.ArrayList(*const schema.Type).empty;
        var inputs = std.ArrayList(*const schema.Type).empty;
        var objects = std.ArrayList(*const schema.Type).empty;
        var enums = std.ArrayList(*const schema.Type).empty;

        defer {
            scalars.deinit(self.allocator);
            inputs.deinit(self.allocator);
            objects.deinit(self.allocator);
            enums.deinit(self.allocator);
        }

        for (self.schema.__schema.types) |*t| {
            const name = t.name orelse continue;
            if (std.mem.startsWith(u8, name, "_")) continue;
            if (isBuiltin(name)) continue;

            switch (t.kind) {
                .SCALAR => try scalars.append(self.allocator, t),
                .INPUT_OBJECT => try inputs.append(self.allocator, t),
                .OBJECT => try objects.append(self.allocator, t),
                .ENUM => try enums.append(self.allocator, t),
                else => {},
            }
        }

        const lessThan = struct {
            fn lessThan(_: void, a: *const schema.Type, b: *const schema.Type) bool {
                return std.mem.lessThan(u8, a.name.?, b.name.?);
            }
        }.lessThan;

        std.mem.sort(*const schema.Type, scalars.items, {}, lessThan);
        std.mem.sort(*const schema.Type, inputs.items, {}, lessThan);
        std.mem.sort(*const schema.Type, objects.items, {}, lessThan);
        std.mem.sort(*const schema.Type, enums.items, {}, lessThan);

        // 1. SCALAR
        for (scalars.items) |t| {
            try self.generateScalar(writer, t);
        }

        // 2. INPUT_OBJECT
        for (inputs.items) |t| {
            try self.generateInput(writer, t);
        }

        // 3. ENUM
        for (enums.items) |t| {
            try self.generateEnum(writer, t);
        }

        // 4. OBJECT (Collect for loadXFromID)
        try writer.writeAll("pub const Client = struct {\n");
        try writer.writeAll("    query_builder: *QueryBuilder,\n");
        try writer.writeAll("    allocator: std.mem.Allocator,\n\n");
        
        for (objects.items) |t| {
            if (std.mem.eql(u8, t.name.?, "Query")) continue;
            // Check if it has an id field
            var has_id = false;
            if (t.fields) |fields| {
                for (fields) |f| {
                    if (std.mem.eql(u8, f.name, "id")) {
                        has_id = true;
                        break;
                    }
                }
            }
            if (has_id) {
                try writer.print("    pub fn load{s}FromID(self: *Client, id_arg: {s}ID) !{s} {{\n", .{ t.name.?, t.name.?, t.name.? });
                try writer.print("        const qb = try self.query_builder.selection(\"load{s}FromID\", .{{ .id = id_arg }});\n", .{t.name.?});
                try writer.print("        return {s}{{ .query_builder = qb, .client = self }};\n", .{t.name.?});
                try writer.writeAll("    }\n\n");
            }
        }

        // Query fields become Client methods
        const query_type = for (objects.items) |t| {
            if (std.mem.eql(u8, t.name.?, "Query")) break t;
        } else unreachable;

        if (query_type.fields) |fields| {
            const sorted_fields = try self.allocator.dupe(schema.Field, fields);
            defer self.allocator.free(sorted_fields);
            std.mem.sort(schema.Field, sorted_fields, {}, struct {
                fn fieldLessThan(_: void, a: schema.Field, b: schema.Field) bool {
                    return std.mem.lessThan(u8, a.name, b.name);
                }
            }.fieldLessThan);

            for (sorted_fields) |f| {
                try self.generateField(writer, "Client", f);
            }
        }
        try writer.writeAll("    pub fn execute(self: *Client, query_builder: *QueryBuilder, comptime ResponseType: type) !ResponseType {\n");
        try writer.writeAll("        _ = self; _ = query_builder;\n");
        try writer.writeAll("        return error.Unimplemented;\n");
        try writer.writeAll("    }\n");
        try writer.writeAll("};\n\n");

        for (objects.items) |t| {
            if (std.mem.eql(u8, t.name.?, "Query")) continue;
            try self.generateObject(writer, t);
        }
    }

    fn isBuiltin(name: []const u8) bool {
        const builtins = [_][]const u8{ "String", "Float", "Int", "Boolean", "DateTime", "ID" };
        for (builtins) |b| {
            if (std.mem.eql(u8, name, b)) return true;
        }
        return false;
    }

    fn generateScalar(self: *Generator, writer: *std.Io.Writer, t: *const schema.Type) !void {
        _ = self;
        if (t.description) |d| {
            try writeDoc(writer, d);
        }
        try writer.print("pub const {s} = struct {{ value: []const u8 }};\n\n", .{t.name.?});
    }

    fn generateInput(self: *Generator, writer: *std.Io.Writer, t: *const schema.Type) !void {
        if (t.description) |d| {
            try writeDoc(writer, d);
        }
        try writer.print("pub const {s} = struct {{\n", .{t.name.?});
        if (t.inputFields) |fields| {
            // Sort fields alphabetically
            const sorted_fields = try self.allocator.dupe(schema.InputValue, fields);
            defer self.allocator.free(sorted_fields);
            std.mem.sort(schema.InputValue, sorted_fields, {}, struct {
                fn inputValueLessThan(_: void, a: schema.InputValue, b: schema.InputValue) bool {
                    return std.mem.lessThan(u8, a.name, b.name);
                }
            }.inputValueLessThan);

            for (sorted_fields) |f| {
                if (f.description) |d| {
                    try writeDoc(writer, d);
                }
                const zigType = try self.toZigType(f.type);
                const field_name = try self.toCamelCase(f.name);
                try writer.print("    {s}: {s},\n", .{ field_name, zigType });
            }
        }
        try writer.writeAll("};\n\n");
    }

    fn generateEnum(self: *Generator, writer: *std.Io.Writer, t: *const schema.Type) !void {
        if (t.description) |d| {
            try writeDoc(writer, d);
        }
        try writer.print("pub const {s} = enum {{\n", .{t.name.?});
        if (t.enumValues) |values| {
            var seen = std.StringArrayMap(void).init(self.allocator);
            for (values) |v| {
                const camelName = try self.toCamelCase(v.name);
                if (seen.contains(camelName)) continue;
                try seen.put(camelName, {});

                if (v.description) |d| {
                    try writeDoc(writer, d);
                }
                try writer.print("    {s},\n", .{camelName});
            }
        }
        try writer.writeAll("\n    pub fn fromString(s: []const u8) !@This() {\n");
        if (t.enumValues) |values| {
            var seen = std.StringArrayMap(void).init(self.allocator);
            for (values) |v| {
                const camelName = try self.toCamelCase(v.name);
                if (seen.contains(camelName)) continue;
                try seen.put(camelName, {});
                try writer.print("        if (std.mem.eql(u8, s, \"{s}\")) return .{s};\n", .{ v.name, camelName });
            }
        }
        try writer.writeAll("        return error.UnknownEnumValue;\n");
        try writer.writeAll("    }\n");
        try writer.writeAll("};\n\n");
    }

    fn generateObject(self: *Generator, writer: *std.Io.Writer, t: *const schema.Type) !void {
        const name = if (std.mem.eql(u8, t.name.?, "Query")) "Client" else t.name.?;
        if (t.description) |d| {
            try writeDoc(writer, d);
        }
        try writer.print("pub const {s} = struct {{\n", .{name});
        try writer.writeAll("    query_builder: *QueryBuilder,\n");
        try writer.writeAll("    client: *Client,\n\n");

        if (t.fields) |fields| {
            // Sort fields alphabetically
            const sorted_fields = try self.allocator.dupe(schema.Field, fields);
            defer self.allocator.free(sorted_fields);
            std.mem.sort(schema.Field, sorted_fields, {}, struct {
                fn fieldLessThan(_: void, a: schema.Field, b: schema.Field) bool {
                    return std.mem.lessThan(u8, a.name, b.name);
                }
            }.fieldLessThan);

            for (sorted_fields) |f| {
                try self.generateField(writer, t.name.?, f);
            }
        }

        try writer.writeAll("};\n\n");
    }

    fn generateField(self: *Generator, writer: *std.Io.Writer, parent_name: []const u8, f: schema.Field) !void {
        if (f.description) |d| {
            try writeDoc(writer, d);
        }
        if (f.isDeprecated) {
            try writer.print("    /// @deprecated: {s}\n", .{f.deprecationReason orelse "No reason provided."});
        }

        // Split args into required and optional
        var required_args = std.ArrayList(schema.InputValue).empty;
        var optional_args = std.ArrayList(schema.InputValue).empty;
        defer required_args.deinit(self.allocator);
        defer optional_args.deinit(self.allocator);

        for (f.args) |arg| {
            if (arg.type.kind == .NON_NULL and arg.defaultValue == null) {
                try required_args.append(self.allocator, arg);
            } else {
                try optional_args.append(self.allocator, arg);
            }
        }

        const return_type = try self.toZigType(f.type);
        const field_fn_name = try self.toCamelCase(f.name);
        try writer.print("    pub fn {s}(self: *@This()", .{field_fn_name});

        for (required_args.items) |arg| {
            const argType = try self.toZigType(arg.type);
            var arg_name = try self.toCamelCase(arg.name);
            if (std.mem.eql(u8, arg_name, "id") or std.mem.eql(u8, arg_name, "name") or std.mem.eql(u8, arg_name, "directory") or std.mem.eql(u8, arg_name, "service") or std.mem.eql(u8, arg_name, "changes") or std.mem.eql(u8, arg_name, "workspace") or std.mem.eql(u8, arg_name, "search") or std.mem.eql(u8, arg_name, "description") or std.mem.eql(u8, arg_name, "sourcemap") or std.mem.eql(u8, arg_name, "env") or std.mem.eql(u8, arg_name, "model") or std.mem.eql(u8, arg_name, "blueprint") or std.mem.eql(u8, arg_name, "dependencies") or std.mem.eql(u8, arg_name, "version") or std.mem.eql(u8, arg_name, "toolchains") or std.mem.eql(u8, arg_name, "hostname") or std.mem.eql(u8, arg_name, "kind") or std.mem.eql(u8, arg_name, "optional") or std.mem.eql(u8, arg_name, "path")) {
                arg_name = try std.fmt.allocPrint(self.allocator, "{s}_arg", .{arg_name});
            }
            try writer.print(", {s}: {s}", .{ arg_name, argType });
        }

        if (optional_args.items.len > 0) {
            try writer.print(", options: struct {{\n", .{});
            for (optional_args.items) |arg| {
                const argType = try self.toZigType(arg.type);
                const arg_name = try self.toCamelCase(arg.name);
                try writer.print("        {s}: {s} = null,\n", .{ arg_name, argType });
            }
            try writer.writeAll("    }") ;
        }

        try writer.print(") !{s} {{\n", .{return_type});
        
        // Start building selection
        try writer.print("        const qb = try self.query_builder.selection(\"{s}\", .{{", .{f.name});
        for (required_args.items) |arg| {
            var arg_name = try self.toCamelCase(arg.name);
            const arg_name_orig = arg_name;
            if (std.mem.eql(u8, arg_name, "id") or std.mem.eql(u8, arg_name, "name") or std.mem.eql(u8, arg_name, "directory") or std.mem.eql(u8, arg_name, "service") or std.mem.eql(u8, arg_name, "changes") or std.mem.eql(u8, arg_name, "workspace") or std.mem.eql(u8, arg_name, "search") or std.mem.eql(u8, arg_name, "description") or std.mem.eql(u8, arg_name, "sourcemap") or std.mem.eql(u8, arg_name, "env") or std.mem.eql(u8, arg_name, "model") or std.mem.eql(u8, arg_name, "blueprint") or std.mem.eql(u8, arg_name, "dependencies") or std.mem.eql(u8, arg_name, "version") or std.mem.eql(u8, arg_name, "toolchains") or std.mem.eql(u8, arg_name, "hostname") or std.mem.eql(u8, arg_name, "kind") or std.mem.eql(u8, arg_name, "optional") or std.mem.eql(u8, arg_name, "path")) {
                arg_name = try std.fmt.allocPrint(self.allocator, "{s}_arg", .{arg_name});
            }
            try writer.print(" .{s} = {s},", .{ arg_name_orig, arg_name });
        }
        if (optional_args.items.len > 0) {
            for (optional_args.items) |arg| {
                const arg_name = try self.toCamelCase(arg.name);
                try writer.print(" .{s} = options.{s},", .{ arg_name, arg_name });
            }
        }
        try writer.writeAll(" });\n");

        // Handle return value decision tree
        if (self.isVoid(f.type)) {
            try writer.writeAll("        _ = try self.client.execute(qb, void);\n");
        } else if (self.isListOf(f.type, .OBJECT)) {
            const inner_type = self.unwrap(f.type).name.?;
            try writer.print("        const ids = try self.client.execute(qb, []const {s}ID);\n", .{inner_type});
            try writer.print("        var results = try self.client.allocator.alloc({s}, ids.len);\n", .{inner_type});
            try writer.print("        for (ids, 0..) |id_val, i| {{\n", .{});
            try writer.print("            results[i] = try self.client.load{s}FromID(id_val);\n", .{inner_type});
            try writer.print("        }}\n", .{});
            try writer.print("        return results;\n", .{});
        } else if (self.isIdType(f.type) and std.mem.eql(u8, self.unwrap(f.type).name.?[0..self.unwrap(f.type).name.?.len-2], parent_name) and !std.mem.eql(u8, f.name, "id")) {
             const inner_type = parent_name;
             try writer.print("        const id_val = try self.client.execute(qb, {s}ID);\n", .{inner_type});
             try writer.print("        return try self.client.load{s}FromID(id_val);\n", .{inner_type});
        } else if (self.isScalar(f.type) or self.isListOf(f.type, .SCALAR)) {
            try writer.print("        return try self.client.execute(qb, {s});\n", .{return_type});
        } else if (self.isEnum(f.type)) {
            try writer.writeAll("        const s = try self.client.execute(qb, []const u8);\n");
            try writer.print("        return try {s}.fromString(s);\n", .{self.unwrap(f.type).name.?});
        } else if (self.isListOf(f.type, .ENUM)) {
            const inner_type = self.unwrap(f.type).name.?;
            try writer.writeAll("        const strings = try self.client.execute(qb, []const []const u8);\n");
            try writer.print("        var results = try self.client.allocator.alloc({s}, strings.len);\n", .{inner_type});
            try writer.print("        for (strings, 0..) |s, i| {{\n", .{});
            try writer.print("            results[i] = try {s}.fromString(s);\n", .{inner_type});
            try writer.print("        }}\n", .{});
            try writer.print("        return results;\n", .{});
        } else {
            // Default: object chaining
            const inner_type = self.unwrap(f.type).name.?;
            try writer.print("        return {s}{{ .query_builder = qb, .client = self.client }};\n", .{inner_type});
        }
        try writer.writeAll("    }\n\n");
    }

    fn isOptional(ref: schema.TypeRef) bool {
        return ref.kind != .NON_NULL;
    }

    fn isScalar(self: *Generator, ref: schema.TypeRef) bool {
        _ = self;
        var curr = &ref;
        if (curr.kind == .NON_NULL) curr = curr.ofType.?;
        return curr.kind == .SCALAR;
    }

    fn isEnum(self: *Generator, ref: schema.TypeRef) bool {
        _ = self;
        var curr = &ref;
        if (curr.kind == .NON_NULL) curr = curr.ofType.?;
        return curr.kind == .ENUM;
    }

    fn isObject(self: *Generator, ref: schema.TypeRef) bool {
        _ = self;
        var curr = &ref;
        if (curr.kind == .NON_NULL) curr = curr.ofType.?;
        return curr.kind == .OBJECT;
    }

    fn isVoid(self: *Generator, ref: schema.TypeRef) bool {
        _ = self;
        var curr = &ref;
        if (curr.kind == .NON_NULL) curr = curr.ofType.?;
        return curr.kind == .SCALAR and std.mem.eql(u8, curr.name.?, "Void");
    }

    fn isIdType(self: *Generator, ref: schema.TypeRef) bool {
        _ = self;
        var curr = &ref;
        if (curr.kind == .NON_NULL) curr = curr.ofType.?;
        return curr.kind == .SCALAR and std.mem.endsWith(u8, curr.name.?, "ID");
    }

    fn isListOf(self: *Generator, ref: schema.TypeRef, kind: schema.TypeKind) bool {
        _ = self;
        var curr = &ref;
        if (curr.kind == .NON_NULL) curr = curr.ofType.?;
        if (curr.kind != .LIST) return false;
        curr = curr.ofType.?;
        if (curr.kind == .NON_NULL) curr = curr.ofType.?;
        return curr.kind == kind;
    }

    fn unwrap(self: *Generator, ref: schema.TypeRef) *const schema.TypeRef {
        _ = self;
        var curr = &ref;
        while (curr.kind == .NON_NULL or curr.kind == .LIST) {
            curr = curr.ofType.?;
        }
        return curr;
    }

    fn toZigType(self: *Generator, ref: schema.TypeRef) ![]const u8 {
        return self.toZigTypeInternal(ref, true);
    }

    fn toZigTypeInternal(self: *Generator, ref: schema.TypeRef, top_level: bool) error{OutOfMemory}![]const u8 {
        if (ref.kind == .NON_NULL) {
            return self.toZigTypeInternal(ref.ofType.?.*, false);
        }
        
        var base_type: []const u8 = undefined;
        if (ref.kind == .LIST) {
            const inner = try self.toZigTypeInternal(ref.ofType.?.*, true);
            base_type = try std.fmt.allocPrint(self.allocator, "[]const {s}", .{inner});
        } else if (ref.name) |n| {
            if (std.mem.eql(u8, n, "String")) {
                base_type = "[]const u8";
            } else if (std.mem.eql(u8, n, "Int")) {
                base_type = "i32";
            } else if (std.mem.eql(u8, n, "Float")) {
                base_type = "f64";
            } else if (std.mem.eql(u8, n, "Boolean")) {
                base_type = "bool";
            } else if (std.mem.eql(u8, n, "Void")) {
                base_type = "void";
            } else {
                base_type = n;
            }
        } else {
            base_type = "anyopaque";
        }

        if (top_level and ref.kind != .NON_NULL) {
            return try std.fmt.allocPrint(self.allocator, "?{s}", .{base_type});
        }
        return base_type;
    }

    fn toCamelCase(self: *Generator, s: []const u8) ![]const u8 {
        var result = std.ArrayList(u8).empty;
        var nextUpper = false;
        for (s, 0..) |c, i| {
            if (c == '_') {
                nextUpper = true;
                continue;
            }
            if (nextUpper) {
                try result.append(self.allocator, std.ascii.toUpper(c));
                nextUpper = false;
            } else {
                if (i == 0) {
                    try result.append(self.allocator, std.ascii.toLower(c));
                } else {
                    try result.append(self.allocator, std.ascii.toLower(c));
                }
            }
        }
        const name = try result.toOwnedSlice(self.allocator);
        if (isKeyword(name)) {
            return try std.fmt.allocPrint(self.allocator, "@\"{s}\"", .{name});
        }
        return name;
    }

    fn toPascalCase(self: *Generator, s: []const u8) ![]const u8 {
        var result = std.ArrayList(u8).empty;
        var nextUpper = true;
        for (s) |c| {
            if (c == '_') {
                nextUpper = true;
                continue;
            }
            if (nextUpper) {
                try result.append(self.allocator, std.ascii.toUpper(c));
                nextUpper = false;
            } else {
                try result.append(self.allocator, std.ascii.toLower(c));
            }
        }
        const name = try result.toOwnedSlice(self.allocator);
        if (isKeyword(name)) {
            return try std.fmt.allocPrint(self.allocator, "@\"{s}\"", .{name});
        }
        return name;
    }

    fn isKeyword(name: []const u8) bool {
        const keywords = [_][]const u8{
            "addrspace", "align", "and", "asm", "async", "await", "break", "catch", "comptime",
            "const", "continue", "defer", "else", "enum", "errdefer", "error", "export", "extern",
            "fn", "for", "if", "inline", "noalias", "noinline", "nosuspend", "opaque", "or",
            "orelse", "packed", "pub", "resume", "return", "linksection", "struct", "suspend",
            "switch", "test", "threadlocal", "try", "union", "unreachable", "usingnamespace",
            "var", "volatile", "while",
        };
        for (keywords) |kw| {
            if (std.mem.eql(u8, name, kw)) return true;
        }
        return false;
    }

    fn writeDoc(writer: *std.Io.Writer, description: []const u8) !void {
        var it = std.mem.splitSequence(u8, description, "\n");
        while (it.next()) |line| {
            try writer.print("/// {s}\n", .{line});
        }
    }
};
